name = "PDBTools"
uuid = "e29189f1-7114-4dbd-93d0-c5673a921a58"
authors = ["Leandro Martinez <leandro@iqm.unicamp.br>"]
version = "0.2.1"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"
